---
- name: "Creates backend app directory"
  file:
    path: ~/backend_app
    state: directory

- name: "Unarchive backend files"
  unarchive:
    src: artifact.tar.gzp
    dest: ~/backend_app

- name: "Install dependencies for project"
  shell: |
    cd ~/backend_app
    npm install
- name: "Executing node with PM2"
  shell: |
    cd ~/backend_app/dist

    cd ../
    npm install
    npm build
    
    sudo npm install forever -g
    sudo npm install ts-node -g
    forever start -c "ts-node   -r tsconfig-paths/register -r dotenv/config src/main.ts" ./
    pm2 start main.js
    
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu